### ISSUE TITLE
[BROKEN LINK]

### ISSUE THREAD

**Issue by Tailgunnnmer** [o3de/o3de.org#2562] opened 2024-06-08 11:21 UTC
## Which page has the broken link?

[]https://www.docs.o3de.org/docs/welcome-guide/

## Which link was broken?

 https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

**Comment by ShaunaGordon** [comment] 2024-08-22 18:16
Duplicate of #2560

**Closed by ShaunaGordon** 2024-08-22 18:16 UTC
Labels: status/duplicate
