### ISSUE TITLE
[BROKEN LINK] NVIDIA PhysX

### ISSUE THREAD

**Issue by Oreloth** [o3de/o3de.org#2572] opened 2024-07-24 11:40 UTC
## Which page has the broken link?

https://o3de.org/gems/

## Which link was broken?

https://www.docs.o3de.org/docs/docs/user-guide/gems/reference/physics/nvidia/physx/

## Know where it should go?

https://www.docs.o3de.org/docs/user-guide/gems/reference/physics/nvidia/physx/

**Comment by ShaunaGordon** [comment] 2024-08-23 16:33
Verified that the link does behave as described, but I've thus far been unable to find where the link is coming from. Needs further digging to see how it's being created.

**Comment by Oreloth** [comment] 2024-08-23 17:46
The link is from [this page](https://o3de.org/gems/).

**Comment by ShaunaGordon** [comment] 2024-08-26 15:11
You have that link already in your initial report. The trouble I'm running into is how it's being created in the source.

**Comment by ShaunaGordon** [comment] 2024-08-26 19:00
Duplicate of #2494

**Closed by ShaunaGordon** 2024-08-26 19:00 UTC
Labels: status/duplicate, kind/website, kind/broken-link
