### ISSUE TITLE
[BROKEN LINK] https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

### ISSUE THREAD

**Issue by Tortenschachtel** [o3de/o3de.org#2563] opened 2024-06-14 20:55 UTC
## Which page has the broken link?

https://www.docs.o3de.org/docs/welcome-guide/
Section "Get Started Tutorials", first tutorial

## Which link was broken?

Title: "Create your first game: Pong!"
Link: https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

**Comment by ShaunaGordon** [comment] 2024-08-22 18:17
Duplicate of #2560

**Closed by ShaunaGordon** 2024-08-22 18:17 UTC
Labels: status/duplicate
