### ISSUE TITLE
[BROKEN LINK]

### ISSUE THREAD

**Issue by yvssva** [o3de/o3de.org#2581] opened 2024-08-20 18:42 UTC
## Which page has the broken link?

 https://www.docs.o3de.org/docs/learning-guide/tutorials/
## Which link was broken?

 https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

## Know where it should go?

 Should appers the tutorial O3DE game: Pong

**Comment by ShaunaGordon** [comment] 2024-08-22 18:04
Duplicate of #2560

**Closed by ShaunaGordon** 2024-08-22 18:04 UTC
Labels: status/duplicate
