### ISSUE TITLE
[BUG][WEBSITE] The right hand side Anchors links should follow the user as they scroll down the page

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de.org#1203] opened 2021-11-18 23:05 UTC
## Describe the bug

When a user is reading a page with the right hand side (RHS) anchor links, as they scroll down to read the content, the RHS anchors should follow along with them.

## Reproduction steps

1. Open a page like: https://o3de.org/docs/user-guide/components/development/reflection/
2. Scroll down the page

## Expected behavior

The RHS anchors should move down the page with you as you read the content

## Screenshots

![Screen-Shot-2021-11-18-at-3 04 26-PM](https://user-images.githubusercontent.com/82846749/142510948-34e0d6fc-983a-4e7c-9f29-c944d377bd5d.jpg)

![Screen Shot 2021-11-18 at 3 04 31 PM](https://user-images.githubusercontent.com/82846749/142510852-beac59b1-7734-486f-91b9-b6ae35a4bca2.png)

**Comment by chanmosq** [comment] 2022-08-24 21:31
Closing because duplicate of an issue reported earlier: https://github.com/o3de/o3de.org/issues/1013

**Closed by chanmosq** 2022-08-24 21:31 UTC
Labels: kind/bug, priority/major, RTE, WF8, kind/website
