### ISSUE TITLE
[Community page] Add a link to Youtube

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de.org#1136] opened 2021-11-03 04:08 UTC
## Describe the feature you'd like available on the website

Add the youtube link to the community page.

## Proposed implementation

Link to O3DE youtube channel: TBD

**Comment by FiniteStateGit** [comment] 2021-11-03 16:27
Duplicate of #1098.

**Comment by sptramer** [comment] 2021-11-03 16:52
Closing in favor of #1098

**Closed by sptramer** 2021-11-03 16:52 UTC
Labels: feature/website, priority/critical, status/duplicate
