### ISSUE TITLE
Multiplayer Template

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de.org#2095] opened 2022-11-16 21:15 UTC
## Describe the issue briefly
The Multiplayer Template should be mentioned somewhere in documentation for users trying to set up multiplayer

## Which page(s) / section(s) are affected?
Please add a link for how to use the Multiplayer Template here so new users dont fall into a rabbit hole of having to edit cmake files + create their own spawners etc.
https://www.o3de.org/docs/user-guide/networking/multiplayer/configuration/

## Does this work have an engineering dependency? What is it?
No

**Comment by chanmosq** [comment] 2023-02-28 21:34
Closing because duplicate of https://github.com/o3de/o3de.org/issues/2052

**Closed by chanmosq** 2023-02-28 21:34 UTC
Labels: feature/networking, kind/documentation, priority/major, sig/network, triage/accepted
