### ISSUE TITLE
[DOCS] Add Hugo build troubleshooting tips

### ISSUE THREAD

**Issue by willihay** [o3de/o3de.org#1722] opened 2022-06-16 22:05 UTC
## Describe the issue briefly

When first setting up Hugo to run on a PC, several people have encountered an error like this:

```
$ hugo server
Start building sites …
hugo v0.100.2-d25cb2943fd94ecf781412aeff9682d5dc62e284+extended windows/amd64 BuildDate=2022-06-08T10:25:57Z VendorInfo=gohugoio
Error: Error building site: TOCSS: failed to transform "blah.sass" (text/x-sass): "D:\o3de.org\assets\sass\custom.sass:26:1": File to import not found or unreadable: bootstrap/scss/functions.
```

Cause: This can happen if you run `hugo server` without installing all the build dependencies. You must run `npm install` from your clone's root directory to install the required dependencies for building the website.

Given that this is not uncommon, we should add some troubleshooting advice to help contributors resolve this issue.

## Which page(s) / section(s) are affected?

Could place a "Troubleshooting" subsection under "Set up Hugo", here: https://www.o3de.org/docs/contributing/to-docs/o3de-docs-repo-setup/#set-up-hugo

**Comment by chanmosq** [comment] 2022-06-22 16:55
One instance of this was caused by an installation of bootstrap version 5. We had to reinstall specifically version 4.6.1. 

Technically, `npm install` should install the right version because it reads it from [package.json](https://github.com/o3de/o3de.org/blob/main/package.json#L6). `"bootstrap": "^4.6.1"` indicates that it will install 4.6.1 or the latest minor patch version.

**Comment by chanmosq** [comment] 2023-02-06 23:18
This is addressed in a **Troubleshooting** section of the o3de.org repo's [README](https://github.com/o3de/o3de.org). It does not need to be in the O3DE Contributing Guide because the Hugo page redirects contributors to go to the README regarding how to set up Hugo.

**Closed by chanmosq** 2023-02-06 23:18 UTC
Labels: kind/enhancement, triage/accepted, kind/contributing
