### ISSUE TITLE
[BROKEN LINK] First Project Tutorial

### ISSUE THREAD

**Issue by tabithajarvis** [o3de/o3de.org#2565] opened 2024-06-19 21:02 UTC
## Which page has the broken link?

https://docs.o3de.org/docs/learning-guide/tutorials/

## Which link was broken?

https://docs.o3de.org/docs/learning-guide/tutorials/first-project/

## Know where it should go?

No

**Comment by ShaunaGordon** [comment] 2024-08-22 18:15
Duplicate of #2560

**Closed by ShaunaGordon** 2024-08-22 18:15 UTC
Labels: status/duplicate
