### ISSUE TITLE
[BROKEN LINK]

### ISSUE THREAD

**Issue by k4ss4n** [o3de/o3de.org#2601] opened 2024-10-01 04:18 UTC
## Which page has the broken link?

https://www.docs.o3de.org/docs/learning-guide/tutorials/

## Which link was broken?

[Create your first O3DE game: Pong](https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/)

**Comment by ShaunaGordon** [comment] 2024-10-04 20:43
Duplicate of #2560 and fix currently in stabilization branch, queued up for upcoming release.

**Closed by ShaunaGordon** 2024-10-04 20:43 UTC
Labels: status/duplicate
