### ISSUE TITLE
[BROKEN LINK]

### ISSUE THREAD

**Issue by illiteratesquid** [o3de/o3de.org#2575] opened 2024-07-29 16:04 UTC
## Which page has the broken link?

[]https://www.docs.o3de.org/docs/welcome-guide/

## Which link was broken?

https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

## Know where it should go?

no i dont, this is literally the first thing i clicked on

**Comment by ShaunaGordon** [comment] 2024-08-22 18:17
Duplicate of #2560

**Closed by ShaunaGordon** 2024-08-22 18:17 UTC
Labels: status/duplicate
