### ISSUE TITLE
Pong tutorial missing [DOCS]

### ISSUE THREAD

**Issue by BlastBlaster17** [o3de/o3de.org#2573] opened 2024-07-27 15:58 UTC
## Describe the issue
The tutorial for building a Pong game is missing. It brings you to a 404 page when you click on it. 

## Impacted page(s)

This page: https://www.docs.o3de.org/docs/learning-guide/tutorials/first-project/

## Expected experience
I expected to just get a tutorial for Pong.

**Comment by ShaunaGordon** [comment] 2024-08-22 18:15
Duplicate of #2560

**Closed by ShaunaGordon** 2024-08-22 18:15 UTC
Labels: status/duplicate
